
# Site settings
title: The Changkat Changi Othello Club
email: jwyazuardi@gmail.com
description: > 
  The Official Website of The Changkat Changi Othello Club.
  baseurl: "" 
url: "http://127.0.0.1:4000"
twitter_username: theccssothelloclub
github_username:  jwyazuardicoding

# Build settings
markdown: kramdown
